### ISSUE TITLE
Exception in "CompleteInput" with UNC paths or when there are no matches

### ISSUE THREAD

**Issue by sba923** [nightroman/PS-GuiCompletion#3]
(originally [here](https://github.com/cspotcode/PS-GuiCompletion/issues/14))

When I hit Tab at a partial UNC path I get an exception in "CompleteInput" and expansion doesn't work:

````

PS❯ gmo guicompletion

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     0.10.0                GuiCompletion                       {Install-GuiCompletion, Invoke-GuiCompletion}



PS❯ gci \\pnjnas\p\photos\classAn exception occurred in custom key handler, see $error for more information: Exception calling "CompleteInput" with "3" argument(s): "Object reference not set to an instance of an object."

PS❯ $error[0] | select *

PSMessageDetails      :
Exception             : System.Management.Automation.MethodInvocationException: Exception calling "CompleteInput" with
                        "3" argument(s): "Object reference not set to an instance of an object."
                         ---> System.NullReferenceException: Object reference not set to an instance of an object.
                           at
                        System.Management.Automation.CompletionCompleters.InvokeScriptArgumentCompleter(ScriptBlock
                        scriptBlock, Object[] argumentsToCompleter, List`1 result)
                           at
                        System.Management.Automation.CompletionCompleters.InvokeScriptArgumentCompleter(ScriptBlock
                        scriptBlock, String commandName, String parameterName, String wordToComplete, CommandAst
                        commandAst, CompletionContext context, List`1 resultList)
                           at System.Management.Automation.CompletionCompleters.NativeCommandArgumentCompletion(String
                        commandName, CompiledCommandParameter parameter, List`1 result, CommandAst commandAst,
                        CompletionContext context, Dictionary`2 boundArguments)
                           at System.Management.Automation.CompletionCompleters.ProcessParameter(String commandName,
                        CommandAst commandAst, CompletionContext context, List`1 result,
                        MergedCompiledCommandParameter parameter, Dictionary`2 boundArguments)
                           at System.Management.Automation.CompletionCompleters.GetArgumentCompletionResultsWithSuccess
                        fulPseudoBinding(CompletionContext context, ArgumentLocation argLocation, CommandAst
                        commandAst)
                           at
                        System.Management.Automation.CompletionCompleters.CompleteCommandArgument(CompletionContext
                        context)
                           at System.Management.Automation.CompletionAnalysis.GetResultForIdentifier(CompletionContext
                        completionContext, Int32& replacementIndex, Int32& replacementLength, Boolean isQuotedString)
                           at System.Management.Automation.CompletionAnalysis.GetResultHelper(CompletionContext
                        completionContext, Int32& replacementIndex, Int32& replacementLength, Boolean isQuotedString)
                           at System.Management.Automation.CompletionAnalysis.GetResults(PowerShell powerShell, Int32&
                        replacementIndex, Int32& replacementLength)
                           at System.Management.Automation.CommandCompletion.CompleteInputImpl(Ast ast, Token[]
                        tokens, IScriptPosition positionOfCursor, Hashtable options)
                           at System.Management.Automation.CommandCompletion.CompleteInput(String input, Int32
                        cursorIndex, Hashtable options)
                           at CallSite.Target(Closure , CallSite , Type , String , Int32 , Hashtable )
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext
                        funcContext, Exception exception)
                           at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame
                        frame)
                           at
                        System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame
                        frame)
                           at
                        System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame
                        frame)
                           at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                           at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object
                        dollarUnderbar, Object inputToProcess)
                           at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
                           at System.Management.Automation.CommandProcessorBase.Complete()
TargetObject          :
CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
FullyQualifiedErrorId : NullReferenceException
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock><End>, <No file>: line 38
                        at Invoke-GuiCompletion,
                        C:\Users\<REDACTED>\OneDrive\Documents\PowerShell\Modules\GuiCompletion\0.10.0\GuiCompletion.psm1:
                        line 24
                        at <ScriptBlock>,
                        C:\Users\<REDACTED>\OneDrive\Documents\PowerShell\Modules\GuiCompletion\0.10.0\GuiCompletion.psm1:
                        line 9
                        at PSConsoleHostReadLine,
                        C:\Users\<REDACTED>\OneDrive\Documents\PowerShell\Modules\PSReadLine\2.2.0\PSReadLine.psm1: line 4
PipelineIterationInfo : {}
````

When GuiCompletion is not loaded, hitting Tab in the same context doesn't do anything (whereas it should find a match):

![image](https://user-images.githubusercontent.com/12860484/111876097-68706800-899d-11eb-9611-e322cd5bb39c.png)

**Comment by nightroman** [comment]
@sba923 I played with this and could not find a reproducible case. Maybe I do not have such a path exactly.
Two questions.

(1) Without GuiCompletion you do not see the failure. But can you see the same or similar error in `$Error`?

(2) Could you please try the following: in `GuiCompletion.psm1` before calling

```powershell
$completion = TabExpansion2 $buffer $cursorPosition
```

change the error preference

```powershell
$ErrorActionPreference = 'Continue'
$completion = TabExpansion2 $buffer $cursorPosition
```

After that, do you still see the problem?

**Comment by sba923** [comment]
Yes ;-(

````

PS❯ gmo GuiCompletion

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     0.10.0                GuiCompletion                       {Install-GuiCompletion, Invoke-GuiCompletion}



PS❯ sls -raw 'ErrorAction|TabExpansion2' (gmo GuiCompletion).Path
$ErrorActionPreference = 'Stop'
                $ErrorActionPreference = 'Continue'
                $completion = TabExpansion2 $buffer $cursorPosition


PS❯ gci //pnjnas/p/photos/classAn exception occurred in custom key handler, see $error for more information: Exception calling "CompleteInput" with "3" argument(s): "Object reference not set to an instance of an object."y]
````

**Comment by nightroman** [comment]
And the question (1)?

**Comment by nightroman** [comment]
OK, I think this should help. Could you please try this (wrap `TabExpansion2` call with try/catch)?

```powershell
		try {
			$completion = TabExpansion2 $buffer $cursorPosition
		}
		catch {
			return
		}
```

**Comment by sba923** [comment]
With

````
try
		{
			$completion = TabExpansion2 $buffer $cursorPosition
			if (!$completion.CompletionMatches)
			{
				return
			}
		}
		catch
		{
			return
		}
````

the red exception message disappears, the behavior is that one gets _without_ GuiCompletion.

Good job!

Now I have to report that tab expansion in those contexts doesn't work in the first place!

**Comment by nightroman** [comment]
Good. You used the slightly different variation than I suggested. Did mine have problems?

**Comment by nightroman** [comment]
Fixed in v0.10.1, thank you for reporting and your cooperation.

**Comment by sba923** [comment]
> Good. You used the slightly different variation than I suggested. Did mine have problems?

Not strictly speaking. But this protects against `TabExpansion2` returning unexpected data (that would cause an exception when accessing the `CompletionMatches` property).

**Comment by sba923** [comment]
> Fixed in v0.10.1, thank you for reporting and your cooperation.

You're very welcome.

**Comment by nightroman** [comment]
> But this protects against TabExpansion2 returning unexpected data (that would cause an exception when accessing the CompletionMatches property).

Maybe. But I do not want to "swallow" these issues before seeing them. I'd like to be "notified" so that they are investigated and fixed or worked around. If none is possible then only we "swallow" them.

**Comment by sba923** [comment]
Good point.
